version: '3'
services:
  postgres:
    container_name: emails-postgres
    image: postgres:latest
    ports:
    - "5434:5432"
    volumes:
    - postgres:/var/lib/postgresql/data
    env_file:
    - docker.env
    networks:
    - postgres

  pgadmin:
    links:
    - postgres:postgres
    container_name: emails-pgadmin
    image: dpage/pgadmin4
    ports:
    - "8082:80"
    volumes:
    - pgadmin-data:/var/lib/pgadmin
    env_file:
    - docker.env
    networks:
    - postgres

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - docker.env


volumes:
  postgres:
  pgadmin-data:

networks:
  postgres:
    driver: bridge